version: '3'

services:
  mysql:
    build: db
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: my-secret-password
    expose:
      - "3306"
  app:
    build: app
    ports: 
      - "8080:8080"