version: '3'

services:
  mysql:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: app
    expose:
      - "3306"
  app:
    build: .
    ports: 
      - "8080:8080"