USE app;

CREATE TABLE BOARD (
    ID int NOT NULL AUTO_INCREMENT, 
    NAME VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE TICKET (
    ID int NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    BOARD_ID int NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (BOARD_ID) REFERENCES BOARD(ID)
)